### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by bascurtiz** [mahyargm/Auto-Tune-Detection#1]
No issue, just a tutorial how to install and use ATD, to get other users going...
...and my way of saying thank you!

[https://www.youtube.com/watch?v=RwdoH8R0ijk](https://www.youtube.com/watch?v=RwdoH8R0ijk)

**Comment by bascurtiz** [comment]
![image](https://github.com/mahyargm/Auto-Tune-Detection/assets/34075088/b7b8b7b1-c16f-4eaf-9ccb-0a62fe8bd4c2)


oops... 
ZeroDivisionError: https://rollbar.com/blog/python-zerodivisionerror/

Fix (too lazy to do a push):
```
    redictions_binary = []
    predictions = []
    with torch.no_grad():
        for feature_vector in features:
            output = model(feature_vector.squeeze(0))
            predictions_binary.append((output >= 0.5))
            predictions.append(output)
            
    if len(predictions) == 0:
        print("Cannot divide by zero")
    else:
        print('Number of Auto-Tuned segments: {}/{}'.format(predictions_binary.count(True), len(predictions_binary)))
        print('The average likelihood: {}'.format(sum(predictions) / len(predictions)))
```
        
...unless something is failing somewhere else, which is not really fixed by the edit?
Processing 10k of files. Will let u know.

**Comment by mahyargm** [comment]
Thank you for getting in touch. It appears that the model didn't detect any segment containing singing vocals in your input. You may want to double-check your input or adjust the energy variable value if necessary.

**Comment by bascurtiz** [comment]
> Thank you for getting in touch. It appears that the model didn't detect any segment containing singing vocals in your input. You may want to double-check your input or adjust the energy variable value if necessary.

5 other vocals were indeed simply silent. 
Attached 6 vocals that were also determined as 'Cannot divide by zero'.
a. `Shut Down` + `We Get Down` sound like stabs, female and male, heavy reverbed, yet vocal I'd say, though low volume...
b. `Space Palace` + `Be Free to Yourself` sound like a vocoder/talkbox, so yeah, heavily auto-tuned, but vocal? uhm no I guess lol?
c. The `Soundgarden` example(s) was were I cought the script at puking the initial error. 
I'm not sure whether it was `Black Hole Sun` or `Burden In My Hand`...

All in all 11 out of 10k+ that determined as 'Cannot divide by zero' is pretty neglectable.
Do with it what you want :)

Link to zipped package with the above examples in flac: https://your.ls/y39n7

**Comment by mahyargm** [comment]
Thank you for the feedback! I will try to fix the problem ASAP.
